apiVersion: v1
kind: Service
metadata:
  name: celery-flower-service
spec:
  type: LoadBalancer
  selector:
    app: celery-flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
